"use client"

import { useCallback, useEffect, useMemo, useState } from "react"
import { useParams, useRouter } from "next/navigation"
import Link from "next/link"
import { ArrowLeft, Building2, CheckCircle2, Home, Loader2, TrendingUp } from "lucide-react"
import { supabase } from "@/lib/supabase"
import { useToast } from "@/hooks/use-toast"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import type { Property, PropertyUnit } from "@/types"

const money=new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:0})
const monthly=(unit:PropertyUnit)=>unit.payment_frequency==="yearly"?unit.rent/12:unit.payment_frequency==="quarterly"?unit.rent/3:unit.payment_frequency==="biannually"?unit.rent/6:unit.rent

export default function ReviewPropertyPage(){const {id}=useParams<{id:string}>();const router=useRouter();const {toast}=useToast();const [property,setProperty]=useState<Property|null>(null);const [units,setUnits]=useState<PropertyUnit[]>([]);const [loading,setLoading]=useState(true);const [publishing,setPublishing]=useState(false)
 const load=useCallback(async()=>{const [{data:propertyData,error:propertyError},{data:unitData,error:unitError}]=await Promise.all([supabase.from("properties").select("*").eq("id",id).single(),supabase.from("property_units").select("*").eq("property_id",id).order("name")]);if(propertyError||unitError)toast({title:"Could not load review",description:propertyError?.message??unitError?.message,variant:"destructive"});setProperty(propertyData as Property|null);setUnits((unitData??[]) as PropertyUnit[]);setLoading(false)},[id,toast]);useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load])
 const stats=useMemo(()=>{const monthlyRevenue=units.reduce((sum,unit)=>sum+monthly(unit),0);return{vacant:units.filter(unit=>unit.availability==="available").length,occupied:units.filter(unit=>unit.availability==="occupied").length,monthly:monthlyRevenue,annual:monthlyRevenue*12}},[units])
 const publish=async()=>{if(!units.length)return toast({title:"Add at least one unit",description:"A multi-unit property cannot be published without a rentable unit.",variant:"destructive"});setPublishing(true);const minimum=Math.min(...units.map(unit=>Number(unit.rent)));const {error}=await supabase.from("properties").update({publication_status:"published",status:stats.vacant>0?"available":"rented",price:minimum}).eq("id",id);setPublishing(false);if(error)return toast({title:"Could not publish property",description:error.message,variant:"destructive"});toast({title:"Property published",description:`${property?.title} is now live.`});router.push("/properties");router.refresh()}
 if(loading)return <div className="flex min-h-64 items-center justify-center"><Loader2 className="h-7 w-7 animate-spin"/></div>;if(!property)return <p>Property not found.</p>
 return <div className="mx-auto max-w-5xl space-y-6 pb-20"><div className="flex items-center gap-3"><Button variant="outline" size="icon" asChild><Link href={`/properties/${id}/units`}><ArrowLeft className="h-4 w-4"/></Link></Button><div><p className="text-sm font-medium text-blue-600">Multi-unit workflow · Step 3 of 3</p><h1 className="text-2xl font-bold sm:text-3xl">Review {property.title}</h1><p className="text-sm text-muted-foreground">Confirm the building and unit portfolio before publication.</p></div></div><Card><CardHeader><CardTitle className="flex items-center gap-2"><Building2 className="h-5 w-5 text-blue-600"/>Building information</CardTitle></CardHeader><CardContent className="grid gap-4 text-sm sm:grid-cols-2"><div><p className="text-muted-foreground">Property type</p><p className="font-medium">{property.type}</p></div><div><p className="text-muted-foreground">Location</p><p className="font-medium">{[property.address,property.city,property.state,property.country].filter(Boolean).join(", ")}</p></div><div><p className="text-muted-foreground">Manager</p><p className="font-medium">{property.manager_name||"Not assigned"}{property.manager_phone?` · ${property.manager_phone}`:""}</p></div><div><p className="text-muted-foreground">Publication</p><Badge variant={property.publication_status==="published"?"default":"secondary"}>{property.publication_status??"draft"}</Badge></div></CardContent></Card>
 <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{([["Total units",units.length,Home],["Vacant units",stats.vacant,CheckCircle2],["Monthly revenue",money.format(stats.monthly),TrendingUp],["Annual revenue",money.format(stats.annual),TrendingUp]] as [string,string|number,typeof Home][]).map(([label,value,Icon])=><Card key={String(label)}><CardContent className="p-4"><Icon className="h-5 w-5 text-blue-600"/><p className="mt-3 text-xl font-bold">{String(value)}</p><p className="text-xs text-muted-foreground">{String(label)}</p></CardContent></Card>)}</div>
 <Card><CardHeader className="flex-row items-center justify-between"><CardTitle>Units</CardTitle><Button variant="outline" size="sm" asChild><Link href={`/properties/${id}/units/new`}>Add unit</Link></Button></CardHeader><CardContent className="divide-y p-0">{units.map(unit=><div key={unit.id} className="flex items-center justify-between gap-3 p-4"><div><p className="font-medium">{unit.name}</p><p className="text-xs text-muted-foreground">{unit.bedrooms} bed · {unit.bathrooms} bath · Floor {unit.floor||"—"}</p></div><div className="text-right"><p className="font-medium">{money.format(unit.rent)}/{unit.payment_frequency}</p><Badge variant="secondary">{unit.availability}</Badge></div></div>)}{!units.length&&<p className="p-8 text-center text-sm text-muted-foreground">No units created yet.</p>}</CardContent></Card>
 <div className="sticky bottom-4 flex justify-end rounded-xl border bg-white/95 p-3 shadow-lg"><Button size="lg" onClick={()=>void publish()} disabled={publishing||property.publication_status==="published"}>{publishing&&<Loader2 className="mr-2 h-4 w-4 animate-spin"/>}{property.publication_status==="published"?"Property published":"Publish property"}</Button></div></div>}
